receivers: ${file:/etc/otelcol-contrib/receivers.yaml}
processors:
  batch/local:
  batch/f5-datafabric:
    send_batch_max_size: 8192
  interval/f5-datafabric:
    interval: 300s
  attributes/f5-datafabric:
    actions:
      - key: dataType
        action: upsert
        value: x-agentic-ai-metric
exporters:
  otlphttp/metrics-local:
    endpoint: http://prometheus:9090/api/v1/otlp
  # Optional: F5 Datafabric exporter (uncomment and set SENSOR_ID, SENSOR_SECRET_TOKEN if needed)
  # otlp/f5-datafabric:
  #   endpoint: us.edge.df.f5.com:443
  #   headers:
  #     Authorization: "kovacs ${env:SENSOR_ID} ${env:SENSOR_SECRET_TOKEN}"
  #     X-F5-OTEL: "GRPC"
  #   tls:
  #     insecure: false
  #     ca_file: /etc/ssl/certs/ca-certificates.pem
  debug/x-agentic-ai:
    verbosity: basic
    sampling_initial: 5
    sampling_thereafter: 200
service:
  telemetry:
    metrics:
      readers:
        - pull:
            exporter:
              prometheus:
                host: '0.0.0.0'
                port: 8888
  pipelines: ${file:/etc/otelcol-contrib/pipelines.yaml}