global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'x-agentic-ai'
    static_configs:
      - targets: ['otel-collector:9090']
  - job_name: 'otel-collector-telemetry'
    static_configs:
      - targets: ['otel-collector:8888']